export const METRIC_THREADS = {
  M1: {
    nominalDiameter: 1,
    pitch: 0.25,
    finePitch: 0.2,
    series: "R10",
  },
  "M1.2": {
    nominalDiameter: 1.2,
    pitch: 0.25,
    finePitch: 0.2,
    series: "R10",
  },
  "M1.4": {
    nominalDiameter: 1.4,
    pitch: 0.3,
    finePitch: 0.2,
    series: "R20",
  },
  "M1.6": {
    nominalDiameter: 1.6,
    pitch: 0.35,
    finePitch: 0.2,
    series: "R10",
  },
  "M1.8": {
    nominalDiameter: 1.8,
    pitch: 0.35,
    finePitch: 0.2,
    series: "R20",
  },
  M2: {
    nominalDiameter: 2,
    pitch: 0.4,
    finePitch: 0.25,
    series: "R10",
  },
  "M2.5": {
    nominalDiameter: 2.5,
    pitch: 0.45,
    finePitch: 0.35,
    series: "R10",
  },
  M3: {
    nominalDiameter: 3,
    pitch: 0.5,
    finePitch: 0.35,
    series: "R10",
  },
  "M3.5": {
    nominalDiameter: 3.5,
    pitch: 0.6,
    finePitch: 0.35,
    series: "R20",
  },
  M4: {
    nominalDiameter: 4,
    pitch: 0.7,
    finePitch: 0.5,
    series: "R10",
  },
  M5: {
    nominalDiameter: 5,
    pitch: 0.8,
    finePitch: 0.5,
    series: "R10",
  },
  M6: {
    nominalDiameter: 6,
    pitch: 1,
    finePitch: 0.75,
    series: "R10",
  },
  M7: {
    nominalDiameter: 7,
    pitch: 1,
    finePitch: 0.75,
    series: "R20",
  },
  M8: {
    nominalDiameter: 8,
    pitch: 1.25,
    finePitch: 1,
    series: "R10",
  },
  M10: {
    nominalDiameter: 10,
    pitch: 1.5,
    finePitch: 1.25,
    series: "R10",
  },
  M12: {
    nominalDiameter: 12,
    pitch: 1.75,
    finePitch: 1.5,
    series: "R10",
  },
  M14: {
    nominalDiameter: 14,
    pitch: 2,
    finePitch: 1.5,
    series: "R20",
  },
  M16: {
    nominalDiameter: 16,
    pitch: 2,
    finePitch: 1.5,
    series: "R10",
  },
  M18: {
    nominalDiameter: 18,
    pitch: 2.5,
    finePitch: 2,
    series: "R20",
  },
  M20: {
    nominalDiameter: 20,
    pitch: 2.5,
    finePitch: 1.5,
    series: "R10",
  },
  M22: {
    nominalDiameter: 22,
    pitch: 2.5,
    finePitch: 1.5,
    series: "R20",
  },
  M24: {
    nominalDiameter: 24,
    pitch: 3,
    finePitch: 2,
    series: "R10",
  },
  M27: {
    nominalDiameter: 27,
    pitch: 3,
    finePitch: 2,
    series: "R20",
  },
  M30: {
    nominalDiameter: 30,
    pitch: 3.5,
    finePitch: 3,
    series: "R10",
  },
  M33: {
    nominalDiameter: 33,
    pitch: 3.5,
    finePitch: 2,
    series: "R20",
  },
  M36: {
    nominalDiameter: 36,
    pitch: 4,
    finePitch: 3,
    series: "R10",
  },
  M39: {
    nominalDiameter: 39,
    pitch: 4,
    finePitch: 3,
    series: "R20",
  },
  M42: {
    nominalDiameter: 42,
    pitch: 4.5,
    finePitch: 3,
    series: "R10",
  },
  M45: {
    nominalDiameter: 45,
    pitch: 4.5,
    finePitch: 3,
    series: "R20",
  },
  M48: {
    nominalDiameter: 48,
    pitch: 5,
    finePitch: 3,
    series: "R10",
  },
  M52: {
    nominalDiameter: 52,
    pitch: 5,
    finePitch: 4,
    series: "R20",
  },
  M56: {
    nominalDiameter: 56,
    pitch: 5.5,
    finePitch: 4,
    series: "R10",
  },
  M60: {
    nominalDiameter: 60,
    pitch: 5.5,
    finePitch: 4,
    series: "R20",
  },
  M64: {
    nominalDiameter: 64,
    pitch: 6,
    finePitch: 4,
    series: "R10",
  },
} as const;

export type MetricThread = keyof typeof METRIC_THREADS;
